trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g pnpm
    cd frontend
    pnpm install --no-frozen-lockfile
    pnpm run build
  displayName: 'Install dependencies and build'

- task: CopyFiles@2
  inputs:
    sourceFolder: '$(System.DefaultWorkingDirectory)/frontend/dist'
    contents: '**'
    targetFolder: '$(Build.ArtifactStagingDirectory)'
    cleanTargetFolder: true
  displayName: 'Copy build files to artifact staging directory'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'drop'
  displayName: 'Publish build artifacts' 