name = "blogger-9849"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[vars]
# Non-sensitive configuration only
AWS_REGION="auto"
AWS_BUCKET_NAME="blogger"
AWS_ENDPOINT="https://1fb4e203bb44690e975dd68809cb9c93.r2.cloudflarestorage.com"
R2_PUBLIC_URL="https://pub-4960f18fba834252a9a3562a3fc94bef.r2.dev"
DATABASE_URL="prisma+postgres://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiMDFKWVczNE1QSjhKTTMxUTBKVlNUVjUzQUQiLCJ0ZW5hbnRfaWQiOiJlMDhjYTNmNTU0OTg3NTkzMTc1YjIxOTQ4Y2EwYmVjYjBhMTdjNjYwODc4N2RkMDJlMTE3ODJmMTQ1YTIyNjdlIiwiaW50ZXJuYWxfc2VjcmV0IjoiYWI5ODc5NzMtMmY4Yy00MDQ2LWJhYTMtMmM2NWNkNzBiNGYyIn0.D9SUO5lkYWbrKrCWbbePD-_vV8_DymfcH2qV8kUpsqI"
JWT_SECRET = "surajsecretCodeBlogger"
AWS_ACCESS_KEY_ID="5260af3aebf06cda71d775425404a8ad"
AWS_SECRET_ACCESS_KEY="55c9041838c9988e80cd249e209969401c92b825dcc4bfa0f2954b7514b7b6ce"