name = "blogger-9849"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[vars]
DATABASE_URL = ""
JWT_SECRET = ""
AWS_REGION = ""
AWS_BUCKET_NAME = ""

# AWS_ACCESS_KEY_ID
# AWS_SECRET_ACCESS_KEY



