name = "blogger-9849"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[vars]
# Non-sensitive configuration only
AWS_REGION=""
AWS_BUCKET_NAME=""
AWS_ENDPOINT=""
R2_PUBLIC_URL=""
DATABASE_URL="prisma+postgres://"
JWT_SECRET = ""
AWS_ACCESS_KEY_ID=""
AWS_SECRET_ACCESS_KEY=""